### ISSUE TITLE
Seems Twitter is broken ;)

### ISSUE THREAD

**Issue by certrik** [ail-project/ail-feeder-twitter#3]
Twint has some issues.

`CRITICAL:root:twint.run:Twint:Feed:noDataExpecting value: line 1 column 1 (char 0)`

https://github.com/twintproject/twint/issues/915

@adulau

**Comment by certrik** [comment]
Ah ... I see ... you know it already ... https://github.com/twintproject/twint/issues/918

**Comment by adulau** [comment]
It was fixed in the recent version of Twint and applied on our fork. This fix might not survive the removal of Twiiter legacy by end of 2020.
